# source /home/mdt-user/phase2_MiniDAQ/config_tcl/ASD_configuration.tcl

set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_trigger_timeout -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_leading -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_master_reset_code -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_pair -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/full_width_res -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/rising_is_leading -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/start_action_setup0 -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/width_select -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/TDC_ID -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/channel_data_debug -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/channel_enable_r -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/disable_event_reset -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_TDC_ID -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_error_notify -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_high_speed -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_legacy -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_new_ttc -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_trigger -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enbale_fake_hit -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/auto_roll_over -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/bypass_bcr_distribution -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/channel_enable_f -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/disable_trigger_from_TTC -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_8b10b -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_direct_bunch_reset -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_error_packet -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_insert -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]] 
set_property OUTPUT_VALUE 000000 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/rising_is_leading -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/rising_is_leading} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 1 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/width_select -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/width_select} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 000000 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/channel_enable_f -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/channel_enable_f} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 000000 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/channel_enable_r -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/channel_enable_r} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 1 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_high_speed -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/enable_high_speed} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_trigger -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/enable_trigger} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 1 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_error_packet -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/enable_error_packet} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]

set_property OUTPUT_VALUE 0 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/channel_data_debug -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/channel_data_debug} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/bypass_bcr_distribution -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/bypass_bcr_distribution} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/auto_roll_over -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/auto_roll_over} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 1 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_8b10b -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/enable_8b10b} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/disable_event_reset -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/disable_event_reset} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/disable_trigger_from_TTC -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/disable_trigger_from_TTC} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_direct_bunch_reset -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/enable_direct_bunch_reset} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_error_notify -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/enable_error_notify} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_insert -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/enable_insert} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_leading -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/enable_leading} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_legacy -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/enable_legacy} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 1 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_master_reset_code -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/enable_master_reset_code} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_new_ttc -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/enable_new_ttc} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 1 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_pair -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/enable_pair} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_TDC_ID -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/enable_TDC_ID} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enable_trigger_timeout -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/enable_trigger_timeout} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/enbale_fake_hit -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/enbale_fake_hit} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/full_width_res -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/full_width_res} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup0_inst"}]]

set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/event_offset -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/bunch_offset -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/coarse_count_offset -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/combine_time_out_config -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/fake_hit_time_interval -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/match_window -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/roll_over -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/start_action_setup1 -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]] 
set_property NAME.SELECT short [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/syn_packet_number -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]] 
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/event_offset -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/bunch_offset -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/coarse_count_offset -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/combine_time_out_config -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/fake_hit_time_interval -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/match_window -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/roll_over -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/start_action_setup1 -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/syn_packet_number -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/bunch_offset -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/bunch_offset} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/coarse_count_offset -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/coarse_count_offset} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
set_property OUTPUT_VALUE 80 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/combine_time_out_config -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/combine_time_out_config} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/event_offset -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/event_offset} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
set_property OUTPUT_VALUE 256 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/fake_hit_time_interval -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/fake_hit_time_interval} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
set_property OUTPUT_VALUE 60 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/match_window -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/match_window} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
set_property OUTPUT_VALUE 4095 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/roll_over -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/roll_over} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
set_property OUTPUT_VALUE 4095 [get_hw_probes inst_Mezz_config/inst_mezz_config_vio/syn_packet_number -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]
commit_hw_vio [get_hw_probes {inst_Mezz_config/inst_mezz_config_vio/syn_packet_number} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"inst_Mezz_config/inst_mezz_config_vio/vio_setup1_inst"}]]



set_property NAME.SELECT short [get_hw_probes JTAG_readback -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]] 
set_property NAME.SELECT short [get_hw_probes mezz_enable_vio -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]] 
set_property NAME.SELECT short [get_hw_probes JTAG_data_length_mezz -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]] 
set_property NAME.SELECT short [get_hw_probes chain_success -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]] 
set_property NAME.SELECT short [get_hw_probes lock_OBUF -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]] 
set_property NAME.SELECT short [get_hw_probes sa_done -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]] 
set_property NAME.SELECT short [get_hw_probes ASD_config -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]] 
set_property NAME.SELECT short [get_hw_probes clk_div -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]] 
set_property NAME.SELECT short [get_hw_probes rst_global -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]] 
set_property NAME.SELECT short [get_hw_probes JTAG_bits_mezz -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]] 
set_property NAME.SELECT short [get_hw_probes JTAG_instr_mezz -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]] 
set_property NAME.SELECT short [get_hw_probes active_chains -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]] 
set_property NAME.SELECT short [get_hw_probes config_done_OBUF -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]] 
set_property NAME.SELECT short [get_hw_probes num_active_ports -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdi_tdo_equal -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]] 
set_property NAME.SELECT short [get_hw_probes TDC_config -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]] 
set_property NAME.SELECT short [get_hw_probes enable_vio_config -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]]
set_property INPUT_VALUE_RADIX BINARY [get_hw_probes active_chains -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]]
set_property INPUT_VALUE_RADIX BINARY [get_hw_probes chain_success -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]]
set_property OUTPUT_VALUE_RADIX BINARY [get_hw_probes mezz_enable_vio -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]]
set_property INPUT_VALUE_RADIX UNSIGNED [get_hw_probes num_active_ports -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]]

set_property OUTPUT_VALUE 010 [get_hw_probes clk_div -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]]
commit_hw_vio [get_hw_probes {clk_div} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]]


#configure all mezz TDC
set_property OUTPUT_VALUE 111111111111111111 [get_hw_probes mezz_enable_vio -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]]
commit_hw_vio [get_hw_probes {mezz_enable_vio} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]]
startgroup
set_property OUTPUT_VALUE 1 [get_hw_probes rst_global -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]]
commit_hw_vio [get_hw_probes {rst_global} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]]
endgroup
after 1000
startgroup
set_property OUTPUT_VALUE 0 [get_hw_probes rst_global -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]]
commit_hw_vio [get_hw_probes {rst_global} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]]
endgroup
after 1000
startgroup
set_property OUTPUT_VALUE 1 [get_hw_probes TDC_config -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]]
commit_hw_vio [get_hw_probes {TDC_config} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]]
endgroup
after 1000
startgroup
set_property OUTPUT_VALUE 0 [get_hw_probes TDC_config -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]]
commit_hw_vio [get_hw_probes {TDC_config} -of_objects [get_hw_vios -of_objects [get_hw_devices xc7a35t_0] -filter {CELL_NAME=~"vio_top_inst"}]]
endgroup
after 1000

