set_property NAME.SELECT short [get_hw_probes downlinkRst_i -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"vio_debug_inst"}]] 
set_property NAME.SELECT short [get_hw_probes lpgbtfpga_uplinkrdy_s -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"vio_debug_inst"}]] 
set_property NAME.SELECT short [get_hw_probes lpgbtfpga_downlinkrdy_s -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"vio_debug_inst"}]] 
set_property NAME.SELECT short [get_hw_probes uplinkRst_i -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"vio_debug_inst"}]] 
startgroup
set_property OUTPUT_VALUE 1 [get_hw_probes downlinkRst_i -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"vio_debug_inst"}]]
commit_hw_vio [get_hw_probes {downlinkRst_i} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"vio_debug_inst"}]]
endgroup
after 1000
startgroup
set_property OUTPUT_VALUE 0 [get_hw_probes downlinkRst_i -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"vio_debug_inst"}]]
commit_hw_vio [get_hw_probes {downlinkRst_i} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"vio_debug_inst"}]]
endgroup
after 1000
startgroup
set_property OUTPUT_VALUE 1 [get_hw_probes uplinkRst_i -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"vio_debug_inst"}]]
commit_hw_vio [get_hw_probes {uplinkRst_i} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"vio_debug_inst"}]]
endgroup
after 1000
startgroup
set_property OUTPUT_VALUE 0 [get_hw_probes uplinkRst_i -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"vio_debug_inst"}]]
commit_hw_vio [get_hw_probes {uplinkRst_i} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"vio_debug_inst"}]]
endgroup
after 1000




set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/coarse_count_offset -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/bc_offset -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/enable_matching -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/enable_relative_trigger_data -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/event_reset -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/match_window -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/reject_offset -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/rollover -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/rst_160_vio -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/search_margin -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/trigger_latency -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/trigger_redge -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]] 
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes tdc_decoder_top_inst/coarse_count_offset -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes tdc_decoder_top_inst/bc_offset -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes tdc_decoder_top_inst/enable_matching -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes tdc_decoder_top_inst/enable_relative_trigger_data -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes tdc_decoder_top_inst/event_reset -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes tdc_decoder_top_inst/match_window -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes tdc_decoder_top_inst/reject_offset -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes tdc_decoder_top_inst/rollover -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes tdc_decoder_top_inst/rst_160_vio -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes tdc_decoder_top_inst/search_margin -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes tdc_decoder_top_inst/trigger_latency -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes tdc_decoder_top_inst/trigger_redge -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]

set_property OUTPUT_VALUE 0 [get_hw_probes tdc_decoder_top_inst/bc_offset -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/bc_offset} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE 4040 [get_hw_probes tdc_decoder_top_inst/coarse_count_offset -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/coarse_count_offset} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes tdc_decoder_top_inst/enable_matching -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/enable_matching} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE 60 [get_hw_probes tdc_decoder_top_inst/match_window -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/match_window} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE 300 [get_hw_probes tdc_decoder_top_inst/reject_offset -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/reject_offset} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE 100 [get_hw_probes tdc_decoder_top_inst/search_margin -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/search_margin} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE 10 [get_hw_probes tdc_decoder_top_inst/trigger_latency -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/trigger_latency} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]

set_property OUTPUT_VALUE 0 [get_hw_probes tdc_decoder_top_inst/enable_relative_trigger_data -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/enable_relative_trigger_data} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes tdc_decoder_top_inst/event_reset -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/event_reset} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE 4095 [get_hw_probes tdc_decoder_top_inst/rollover -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/rollover} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes tdc_decoder_top_inst/rst_160_vio -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/rst_160_vio} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes tdc_decoder_top_inst/trigger_redge -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/trigger_redge} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_trigger_inst"}]]



set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/hit_inv -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/delay_mask -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/enable_hit -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/enable_internal_trigger -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/hit_delay -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/hit_interval -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/hit_mask -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/hit_single -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/hit_trigger_ratio -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/width_hit -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]] 
set_property OUTPUT_VALUE_RADIX BINARY [get_hw_probes tdc_decoder_top_inst/delay_mask -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
set_property OUTPUT_VALUE_RADIX BINARY [get_hw_probes tdc_decoder_top_inst/hit_mask -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes tdc_decoder_top_inst/hit_delay -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes tdc_decoder_top_inst/hit_interval -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes tdc_decoder_top_inst/hit_trigger_ratio -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes tdc_decoder_top_inst/width_hit -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
set_property OUTPUT_VALUE 000000000000000000000000 [get_hw_probes tdc_decoder_top_inst/delay_mask -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/delay_mask} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
set_property OUTPUT_VALUE 400 [get_hw_probes tdc_decoder_top_inst/hit_interval -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/hit_interval} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes tdc_decoder_top_inst/hit_delay -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/hit_delay} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
set_property OUTPUT_VALUE 111111111111111111111111 [get_hw_probes tdc_decoder_top_inst/hit_mask -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/hit_mask} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
set_property OUTPUT_VALUE 1 [get_hw_probes tdc_decoder_top_inst/hit_trigger_ratio -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/hit_trigger_ratio} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
set_property OUTPUT_VALUE 10 [get_hw_probes tdc_decoder_top_inst/width_hit -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/width_hit} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes tdc_decoder_top_inst/enable_hit -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/enable_hit} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes tdc_decoder_top_inst/enable_internal_trigger -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/enable_internal_trigger} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
set_property OUTPUT_VALUE 1 [get_hw_probes tdc_decoder_top_inst/hit_inv -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/hit_inv} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes tdc_decoder_top_inst/hit_single -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/hit_single} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]


set_property NAME.SELECT short [get_hw_probes {tdc_decoder_top_inst/tdc_received_40bit_dline1[2]} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_BER_inst"}]] 
set_property NAME.SELECT short [get_hw_probes {tdc_decoder_top_inst/tdc_error_bit_dline0[1]} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_BER_inst"}]] 
set_property NAME.SELECT short [get_hw_probes {tdc_decoder_top_inst/tdc_error_bit_dline0[2]} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_BER_inst"}]] 
set_property NAME.SELECT short [get_hw_probes {tdc_decoder_top_inst/tdc_error_bit_dline0[3]} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_BER_inst"}]] 
set_property NAME.SELECT short [get_hw_probes {tdc_decoder_top_inst/tdc_error_bit_dline1[1]} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_BER_inst"}]] 
set_property NAME.SELECT short [get_hw_probes {tdc_decoder_top_inst/tdc_error_bit_dline1[2]} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_BER_inst"}]] 
set_property NAME.SELECT short [get_hw_probes {tdc_decoder_top_inst/tdc_error_bit_dline1[3]} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_BER_inst"}]] 
set_property NAME.SELECT short [get_hw_probes {tdc_decoder_top_inst/tdc_received_40bit_dline1[1]} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_BER_inst"}]] 
set_property NAME.SELECT short [get_hw_probes {tdc_decoder_top_inst/tdc_received_40bit_dline1[3]} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_BER_inst"}]] 
set_property NAME.SELECT short [get_hw_probes {tdc_decoder_top_inst/tdc_received_40bit_dline0[1]} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_BER_inst"}]] 
set_property NAME.SELECT short [get_hw_probes {tdc_decoder_top_inst/tdc_received_40bit_dline0[2]} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_BER_inst"}]] 
set_property NAME.SELECT short [get_hw_probes {tdc_decoder_top_inst/tdc_received_40bit_dline0[3]} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_BER_inst"}]] 
set_property INPUT_VALUE_RADIX UNSIGNED [get_hw_probes {tdc_decoder_top_inst/tdc_error_bit_dline0[1]} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_BER_inst"}]]
set_property INPUT_VALUE_RADIX UNSIGNED [get_hw_probes {tdc_decoder_top_inst/tdc_error_bit_dline0[2]} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_BER_inst"}]]
set_property INPUT_VALUE_RADIX UNSIGNED [get_hw_probes {tdc_decoder_top_inst/tdc_error_bit_dline0[3]} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_BER_inst"}]]
set_property INPUT_VALUE_RADIX UNSIGNED [get_hw_probes {tdc_decoder_top_inst/tdc_error_bit_dline1[1]} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_BER_inst"}]]
set_property INPUT_VALUE_RADIX UNSIGNED [get_hw_probes {tdc_decoder_top_inst/tdc_error_bit_dline1[2]} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_BER_inst"}]]
set_property INPUT_VALUE_RADIX UNSIGNED [get_hw_probes {tdc_decoder_top_inst/tdc_error_bit_dline1[3]} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_BER_inst"}]]

set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/enable_320M -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/correct_counter_th -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/enable_K28_1 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/global_rst -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/locked_dline0 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/locked_dline1 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/ttc_bc_reset_vio -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/ttc_event_reset_vio -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]] 
set_property NAME.SELECT short [get_hw_probes tdc_decoder_top_inst/ttc_master_reset_vio -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]] 
set_property INPUT_VALUE_RADIX BINARY [get_hw_probes tdc_decoder_top_inst/locked_dline0 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]]
set_property INPUT_VALUE_RADIX BINARY [get_hw_probes tdc_decoder_top_inst/locked_dline1 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]]
set_property OUTPUT_VALUE_RADIX UNSIGNED [get_hw_probes tdc_decoder_top_inst/correct_counter_th -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]]
set_property OUTPUT_VALUE 1000000 [get_hw_probes tdc_decoder_top_inst/correct_counter_th -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/correct_counter_th} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]]
set_property OUTPUT_VALUE 1 [get_hw_probes tdc_decoder_top_inst/enable_320M -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/enable_320M} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]]
set_property OUTPUT_VALUE 0 [get_hw_probes tdc_decoder_top_inst/enable_K28_1 -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/enable_K28_1} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]]



set_property OUTPUT_VALUE 1 [get_hw_probes tdc_decoder_top_inst/enable_internal_trigger -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/enable_internal_trigger} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
startgroup
set_property OUTPUT_VALUE 1 [get_hw_probes tdc_decoder_top_inst/global_rst -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/global_rst} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]]
endgroup
after 2000
startgroup
set_property OUTPUT_VALUE 0 [get_hw_probes tdc_decoder_top_inst/global_rst -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/global_rst} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_40M_inst"}]]
endgroup
after 3000
set_property OUTPUT_VALUE 0 [get_hw_probes tdc_decoder_top_inst/enable_internal_trigger -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]
commit_hw_vio [get_hw_probes {tdc_decoder_top_inst/enable_internal_trigger} -of_objects [get_hw_vios -of_objects [get_hw_devices xcku035_0] -filter {CELL_NAME=~"tdc_decoder_top_inst/vio_hit_inst"}]]