/**
 * @file TabPanel.h
 *
 * @brief Wrapper for TGTab that better handles associations with menubar
 * options.
 *
 * @author Robert Myers
 * Contact: romyers@umich.edu
 */

#pragma once

#include <string>

#include "TGTab.h"
#include "TGLabel.h"

#include "../Components/Menu.h"
#include "../Components/Submenu.h"
#include "UITab.h"

/*
 * NOTE: New tabs should inherit from UITab.h. They can be added into the GUI
 *       by building them in the implementation of AttachToMenu(). See that
 *       implementation for more notes.
 */

class TabPanel : public TGTab {

public:

/**
	 * Constructor.
	 * 
	 * @param width The width of constituent tab windows.
	 * 
	 * @param height The height of constituent tab windows.
     * 
     * @param menuBar The menu to attach the tab panel to. If a menubar is
     * specified, a submenu will be added to the menu bar that provides options
     * allowing the user to open tabs.
     */
	TabPanel(const TGWindow *p, int width, int height, Menu *menuBar = nullptr);

	/**
	 * Internal use only. Signal handler.
	 */
	virtual void handleCloseTab(int id);

	/**
	 * Internal use only.
	 */
	virtual void makeConnections();

    /**
	 * Returns true if a tab with the given title exists, and false otherwise.
     * 
     * @param label The title of the tab to check for.
	 */
    bool hasTab(const std::string &label);

    virtual void update();

private:

	// A landing page opened when the program starts
	TGCompositeFrame *baseTab;

		TGLabel *baseLabel;

    // These are submenus generated by tab panel.
    Submenu *tabMenu;

        Submenu *adcMenu;
        Submenu *tdcMenu;

    int adcChannelPlotCount;
    int tdcChannelPlotCount;

	void buildTab(const std::string &title, UITab *tab);

	void AttachToMenu(Menu *menuBar);

    bool isAttached();

    int width;
    int height;

};